### ISSUE TITLE
分析2018政府工作报告中的高频词，报错说没有“module 'tools' has no attribute 'get_bs'”

### ISSUE THREAD

**Issue by Licko0909** [coder-pig/ReptileSomething#4]
你好，我看到了你这篇，非常棒，想试一下， 分析2018政府工作报告中的高频词
https://www.zybuluo.com/coder-pig/note/1066957

但是出现报错说没有“module 'tools' has no attribute 'get_bs'”

![image](https://user-images.githubusercontent.com/27897166/55700269-33151e80-5a01-11e9-9030-0d4dcaa381a3.png)

**Comment by coder-pig** [comment]
漏掉文件了啊，tools.py文件，import下就好
